---
# tasks file for vector-role
- name: Install sudo
  yum:
    name: sudo
    state: present
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_major_version }}/vector-{{ vector_minor_version }}.{{ vector_arch }}.rpm"
    dest: ./vector-{{ vector_minor_version }}.{{ vector_arch }}.rpm
- name: Install vector packages
  ansible.builtin.yum:
    name:
      - vector-{{ vector_minor_version }}.{{ vector_arch }}.rpm
    disable_gpg_check: true
